version: '3'

services:

  app:
    build: .
    container_name: app
    entrypoint: dockerize -template ./.docker/app/nginx.tmpl:./.docker/nginx/nginx.conf -wait tcp://db:3306 -timeout 60s ./.docker/entrypoint.sh
    volumes:
      - .:/var/www
    environment:
      - NGINX_HOST=app
      - NGINX_PORT=9000
    networks:
      - app-network
    depends_on:
      - db
      - redis

  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./public:/var/www/public
    networks:
      - app-network
    depends_on:
      - app

  db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
